/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/mfdoom.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Mask002_cell.geometry}
        material={nodes.Mask002_cell.material}
        position={[-0.3, 4.74, 1.73]}
      />
      <mesh
        geometry={nodes.Mask002_cell001.geometry}
        material={nodes.Mask002_cell001.material}
        position={[-1.1, -0.04, 1.1]}
      />
      <mesh
        geometry={nodes.Mask002_cell002.geometry}
        material={nodes.Mask002_cell002.material}
        position={[1.35, 3.19, 1.04]}
      />
      <mesh
        geometry={nodes.Mask002_cell003.geometry}
        material={nodes.Mask002_cell003.material}
        position={[-1, 0.98, 1.44]}
      />
      <mesh
        geometry={nodes.Mask002_cell004.geometry}
        material={nodes.Mask002_cell004.material}
        position={[0.56, 4.65, 1.7]}
      />
      <mesh
        geometry={nodes.Mask002_cell005.geometry}
        material={nodes.Mask002_cell005.material}
        position={[2.25, 3.7, -0.76]}
      />
      <mesh
        geometry={nodes.Mask002_cell006.geometry}
        material={nodes.Mask002_cell006.material}
        position={[0.83, 2.9, 1.46]}
      />
      <mesh
        geometry={nodes.Mask002_cell007.geometry}
        material={nodes.Mask002_cell007.material}
        position={[1.33, 4.21, -1.93]}
      />
      <mesh
        geometry={nodes.Mask002_cell008.geometry}
        material={nodes.Mask002_cell008.material}
        position={[1.91, 4, 0.45]}
      />
      <mesh
        geometry={nodes.Mask002_cell009.geometry}
        material={nodes.Mask002_cell009.material}
        position={[1.67, 3.16, 0.8]}
      />
      <mesh
        geometry={nodes.Mask002_cell010.geometry}
        material={nodes.Mask002_cell010.material}
        position={[-1.95, 3.4, 0.46]}
      />
      <mesh
        geometry={nodes.Mask002_cell011.geometry}
        material={nodes.Mask002_cell011.material}
        position={[-2.3, 3.11, -0.25]}
      />
      <mesh
        geometry={nodes.Mask002_cell012.geometry}
        material={nodes.Mask002_cell012.material}
        position={[-0.18, 6.32, 0.08]}
      />
      <mesh
        geometry={nodes.Mask002_cell013.geometry}
        material={nodes.Mask002_cell013.material}
        position={[1.37, 0.81, 0.8]}
      />
      <mesh
        geometry={nodes.Mask002_cell014.geometry}
        material={nodes.Mask002_cell014.material}
        position={[-2.03, 4.14, 0.38]}
      />
      <mesh
        geometry={nodes.Mask002_cell015.geometry}
        material={nodes.Mask002_cell015.material}
        position={[-0.63, 6.2, 1.5]}
      />
      <mesh
        geometry={nodes.Mask002_cell016.geometry}
        material={nodes.Mask002_cell016.material}
        position={[-1.25, 4.63, -2.09]}
      />
      <mesh
        geometry={nodes.Mask002_cell017.geometry}
        material={nodes.Mask002_cell017.material}
        position={[1.04, 5.35, 1.33]}
      />
      <mesh
        geometry={nodes.Mask002_cell018.geometry}
        material={nodes.Mask002_cell018.material}
        position={[1.47, 4.53, 1.19]}
      />
      <mesh
        geometry={nodes.Mask002_cell019.geometry}
        material={nodes.Mask002_cell019.material}
        position={[-0.33, 5.42, 1.72]}
      />
      <mesh
        geometry={nodes.Mask002_cell020.geometry}
        material={nodes.Mask002_cell020.material}
        position={[-0.83, 1.85, 1.5]}
      />
      <mesh
        geometry={nodes.Mask002_cell021.geometry}
        material={nodes.Mask002_cell021.material}
        position={[0.64, 6.22, 1.53]}
      />
      <mesh
        geometry={nodes.Mask002_cell022.geometry}
        material={nodes.Mask002_cell022.material}
        position={[0.09, 4.02, 1.82]}
      />
      <mesh
        geometry={nodes.Mask002_cell023.geometry}
        material={nodes.Mask002_cell023.material}
        position={[-0.44, 2.53, 1.8]}
      />
      <mesh
        geometry={nodes.Mask002_cell024.geometry}
        material={nodes.Mask002_cell024.material}
        position={[1.72, 5.61, 0.57]}
      />
      <mesh
        geometry={nodes.Mask002_cell025.geometry}
        material={nodes.Mask002_cell025.material}
        position={[1.48, 2.07, 0.84]}
      />
      <mesh
        geometry={nodes.Mask002_cell026.geometry}
        material={nodes.Mask002_cell026.material}
        position={[-1.43, 4.45, 1.22]}
      />
      <mesh
        geometry={nodes.Mask002_cell027.geometry}
        material={nodes.Mask002_cell027.material}
        position={[-0.17, 4.22, 1.59]}
      />
      <mesh
        geometry={nodes.Mask002_cell028.geometry}
        material={nodes.Mask002_cell028.material}
        position={[0.95, -0.01, 1.39]}
      />
      <mesh
        geometry={nodes.Mask002_cell029.geometry}
        material={nodes.Mask002_cell029.material}
        position={[-1.78, 4.51, 0.86]}
      />
      <mesh
        geometry={nodes.Mask002_cell030.geometry}
        material={nodes.Mask002_cell030.material}
        position={[-1.27, 0.26, 0.84]}
      />
      <mesh
        geometry={nodes.Mask002_cell031.geometry}
        material={nodes.Mask002_cell031.material}
        position={[-0.08, 3.22, 1.98]}
      />
      <mesh
        geometry={nodes.Mask002_cell032.geometry}
        material={nodes.Mask002_cell032.material}
        position={[1.17, 6.08, -0.49]}
      />
      <mesh
        geometry={nodes.Mask002_cell033.geometry}
        material={nodes.Mask002_cell033.material}
        position={[-1.7, 5.74, -0.59]}
      />
      <mesh
        geometry={nodes.Mask002_cell034.geometry}
        material={nodes.Mask002_cell034.material}
        position={[2.33, 3.92, -0.31]}
      />
      <mesh
        geometry={nodes.Mask002_cell035.geometry}
        material={nodes.Mask002_cell035.material}
        position={[-2.02, 5, -1.42]}
      />
      <mesh
        geometry={nodes.Mask002_cell036.geometry}
        material={nodes.Mask002_cell036.material}
        position={[0.19, 2.86, 1.93]}
      />
      <mesh
        geometry={nodes.Mask002_cell037.geometry}
        material={nodes.Mask002_cell037.material}
        position={[2.19, 5.07, -0.76]}
      />
      <mesh
        geometry={nodes.Mask002_cell038.geometry}
        material={nodes.Mask002_cell038.material}
        position={[-2.18, 5.08, -0.87]}
      />
      <mesh
        geometry={nodes.Mask002_cell039.geometry}
        material={nodes.Mask002_cell039.material}
        position={[-0.18, 3.85, 1.63]}
      />
      <mesh
        geometry={nodes.Mask002_cell040.geometry}
        material={nodes.Mask002_cell040.material}
        position={[0.95, 4.27, 1.45]}
      />
      <mesh
        geometry={nodes.Mask002_cell041.geometry}
        material={nodes.Mask002_cell041.material}
        position={[-0.11, 2.01, 1.85]}
      />
      <mesh
        geometry={nodes.Mask002_cell042.geometry}
        material={nodes.Mask002_cell042.material}
        position={[0.08, 3.49, 1.75]}
      />
      <mesh
        geometry={nodes.Mask002_cell043.geometry}
        material={nodes.Mask002_cell043.material}
        position={[-1.08, 3.2, 1.11]}
      />
      <mesh
        geometry={nodes.Mask002_cell044.geometry}
        material={nodes.Mask002_cell044.material}
        position={[-0.82, 4.37, -2.23]}
      />
      <mesh
        geometry={nodes.Mask002_cell045.geometry}
        material={nodes.Mask002_cell045.material}
        position={[-2.35, 4.77, -0.39]}
      />
      <mesh
        geometry={nodes.Mask002_cell046.geometry}
        material={nodes.Mask002_cell046.material}
        position={[-1.47, 2.06, 0.86]}
      />
      <mesh
        geometry={nodes.Mask002_cell047.geometry}
        material={nodes.Mask002_cell047.material}
        position={[-1.73, 4.37, -1.71]}
      />
      <mesh
        geometry={nodes.Mask002_cell048.geometry}
        material={nodes.Mask002_cell048.material}
        position={[-1.29, 5.41, 1.12]}
      />
      <mesh
        geometry={nodes.Mask002_cell049.geometry}
        material={nodes.Mask002_cell049.material}
        position={[0.27, 2.27, 1.86]}
      />
      <mesh
        geometry={nodes.Mask002_cell050.geometry}
        material={nodes.Mask002_cell050.material}
        position={[-1.49, 5.87, 0.68]}
      />
      <mesh
        geometry={nodes.Mask002_cell051.geometry}
        material={nodes.Mask002_cell051.material}
        position={[2.01, 4.29, 0.58]}
      />
      <mesh
        geometry={nodes.Mask002_cell052.geometry}
        material={nodes.Mask002_cell052.material}
        position={[2.34, 3.52, -0.59]}
      />
      <mesh
        geometry={nodes.Mask002_cell053.geometry}
        material={nodes.Mask002_cell053.material}
        position={[-0.96, 2.9, 1.39]}
      />
      <mesh
        geometry={nodes.Mask002_cell054.geometry}
        material={nodes.Mask002_cell054.material}
        position={[-0.91, 4.26, 1.47]}
      />
      <mesh
        geometry={nodes.Mask002_cell055.geometry}
        material={nodes.Mask002_cell055.material}
        position={[-1.35, 3.11, 1.11]}
      />
      <mesh
        geometry={nodes.Mask002_cell056.geometry}
        material={nodes.Mask002_cell056.material}
        position={[-1.16, 2.09, 1.31]}
      />
      <mesh
        geometry={nodes.Mask002_cell057.geometry}
        material={nodes.Mask002_cell057.material}
        position={[-1.38, 1.02, 0.81]}
      />
      <mesh
        geometry={nodes.Mask002_cell058.geometry}
        material={nodes.Mask002_cell058.material}
        position={[-2.15, 4.88, 0.34]}
      />
      <mesh
        geometry={nodes.Mask002_cell059.geometry}
        material={nodes.Mask002_cell059.material}
        position={[-0.18, 4.01, 1.79]}
      />
      <mesh
        geometry={nodes.Mask002_cell060.geometry}
        material={nodes.Mask002_cell060.material}
        position={[2.3, 4.4, -0.17]}
      />
      <mesh
        geometry={nodes.Mask002_cell061.geometry}
        material={nodes.Mask002_cell061.material}
        position={[2.05, 5.47, 0.06]}
      />
      <mesh
        geometry={nodes.Mask002_cell062.geometry}
        material={nodes.Mask002_cell062.material}
        position={[0.64, 6.2, 0.14]}
      />
      <mesh
        geometry={nodes.Mask002_cell063.geometry}
        material={nodes.Mask002_cell063.material}
        position={[0.34, 4.39, 1.78]}
      />
      <mesh
        geometry={nodes.Mask002_cell064.geometry}
        material={nodes.Mask002_cell064.material}
        position={[1.25, 5.91, -0.08]}
      />
      <mesh
        geometry={nodes.Mask002_cell065.geometry}
        material={nodes.Mask002_cell065.material}
        position={[2.26, 5.21, -0.09]}
      />
      <mesh
        geometry={nodes.Mask002_cell066.geometry}
        material={nodes.Mask002_cell066.material}
        position={[2.1, 3.55, 0.3]}
      />
      <mesh
        geometry={nodes.Mask002_cell067.geometry}
        material={nodes.Mask002_cell067.material}
        position={[-0.46, 1.8, 1.64]}
      />
      <mesh
        geometry={nodes.Mask002_cell068.geometry}
        material={nodes.Mask002_cell068.material}
        position={[1.16, -0.01, 1.06]}
      />
      <mesh
        geometry={nodes.Mask002_cell069.geometry}
        material={nodes.Mask002_cell069.material}
        position={[0.63, 4.23, 1.62]}
      />
      <mesh
        geometry={nodes.Mask002_cell070.geometry}
        material={nodes.Mask002_cell070.material}
        position={[0.09, 6.34, 1.71]}
      />
      <mesh
        geometry={nodes.Mask002_cell071.geometry}
        material={nodes.Mask002_cell071.material}
        position={[-1.86, 2.49, 0.23]}
      />
      <mesh
        geometry={nodes.Mask002_cell072.geometry}
        material={nodes.Mask002_cell072.material}
        position={[0.88, 0.02, 1.56]}
      />
      <mesh
        geometry={nodes.Mask002_cell073.geometry}
        material={nodes.Mask002_cell073.material}
        position={[2.29, 3.06, -0.21]}
      />
      <mesh
        geometry={nodes.Mask002_cell074.geometry}
        material={nodes.Mask002_cell074.material}
        position={[-2.07, 2.77, 0.11]}
      />
      <mesh
        geometry={nodes.Mask002_cell075.geometry}
        material={nodes.Mask002_cell075.material}
        position={[-0.29, 4.19, -2.33]}
      />
      <mesh
        geometry={nodes.Mask002_cell076.geometry}
        material={nodes.Mask002_cell076.material}
        position={[1.02, 0.85, 1.41]}
      />
      <mesh
        geometry={nodes.Mask002_cell077.geometry}
        material={nodes.Mask002_cell077.material}
        position={[1.28, 0.03, 0.76]}
      />
      <mesh
        geometry={nodes.Mask002_cell078.geometry}
        material={nodes.Mask002_cell078.material}
        position={[2.39, 4.93, -0.26]}
      />
      <mesh
        geometry={nodes.Mask002_cell079.geometry}
        material={nodes.Mask002_cell079.material}
        position={[-0.45, 4.23, 1.69]}
      />
      <mesh
        geometry={nodes.Mask002_cell080.geometry}
        material={nodes.Mask002_cell080.material}
        position={[-2.31, 3.88, -0.49]}
      />
      <mesh
        geometry={nodes.Mask002_cell081.geometry}
        material={nodes.Mask002_cell081.material}
        position={[0.91, 1.89, 1.45]}
      />
      <mesh
        geometry={nodes.Mask002_cell082.geometry}
        material={nodes.Mask002_cell082.material}
        position={[0.29, 6.24, 0.3]}
      />
      <mesh
        geometry={nodes.Mask002_cell083.geometry}
        material={nodes.Mask002_cell083.material}
        position={[-1.97, 5.49, 0.19]}
      />
      <mesh
        geometry={nodes.Mask002_cell084.geometry}
        material={nodes.Mask002_cell084.material}
        position={[2.43, 3.54, -0.22]}
      />
      <mesh
        geometry={nodes.Mask002_cell085.geometry}
        material={nodes.Mask002_cell085.material}
        position={[0.97, 4.51, -2.21]}
      />
      <mesh
        geometry={nodes.Mask002_cell086.geometry}
        material={nodes.Mask002_cell086.material}
        position={[1.96, 2.6, 0.24]}
      />
      <mesh
        geometry={nodes.Mask002_cell087.geometry}
        material={nodes.Mask002_cell087.material}
        position={[-0.5, 3.25, 1.56]}
      />
      <mesh
        geometry={nodes.Mask002_cell088.geometry}
        material={nodes.Mask002_cell088.material}
        position={[1.89, 4.94, -1.63]}
      />
      <mesh
        geometry={nodes.Mask002_cell089.geometry}
        material={nodes.Mask002_cell089.material}
        position={[1.15, 3.05, 1.24]}
      />
      <mesh
        geometry={nodes.Mask002_cell090.geometry}
        material={nodes.Mask002_cell090.material}
        position={[-2.23, 2.72, -0.06]}
      />
      <mesh
        geometry={nodes.Mask002_cell091.geometry}
        material={nodes.Mask002_cell091.material}
        position={[0.46, 4.14, -2.27]}
      />
      <mesh
        geometry={nodes.Mask002_cell092.geometry}
        material={nodes.Mask002_cell092.material}
        position={[-1.69, 2.55, 0.66]}
      />
      <mesh
        geometry={nodes.Mask002_cell093.geometry}
        material={nodes.Mask002_cell093.material}
        position={[2.11, 4.17, -1.22]}
      />
      <mesh
        geometry={nodes.Mask002_cell094.geometry}
        material={nodes.Mask002_cell094.material}
        position={[0.21, 4.09, 1.63]}
      />
      <mesh
        geometry={nodes.Mask002_cell095.geometry}
        material={nodes.Mask002_cell095.material}
        position={[-2.04, 2.64, 0.32]}
      />
      <mesh
        geometry={nodes.Mask002_cell096.geometry}
        material={nodes.Mask002_cell096.material}
        position={[2.05, 4.86, 0.52]}
      />
      <mesh
        geometry={nodes.Mask002_cell097.geometry}
        material={nodes.Mask002_cell097.material}
        position={[-2.27, 5.15, -0.5]}
      />
      <mesh
        geometry={nodes.Mask002_cell098.geometry}
        material={nodes.Mask002_cell098.material}
        position={[-1.03, 4.09, -2.07]}
      />
      <mesh
        geometry={nodes.Mask002_cell099.geometry}
        material={nodes.Mask002_cell099.material}
        position={[1.74, 4.32, 0.86]}
      />
      <mesh
        geometry={nodes.Mask002_cell104.geometry}
        material={nodes.Mask002_cell104.material}
        position={[-1.01, 6.09, -0.12]}
      />
      <mesh
        geometry={nodes.Mask002_cell105.geometry}
        material={nodes.Mask002_cell105.material}
        position={[1.75, 5.7, -0.44]}
      />
      <mesh
        geometry={nodes.Mask002_cell106.geometry}
        material={nodes.Mask002_cell106.material}
        position={[1.18, 6.04, 0.99]}
      />
      <mesh
        geometry={nodes.Mask002_cell107.geometry}
        material={nodes.Mask002_cell107.material}
        position={[1.39, 5.92, 0.75]}
      />
      <mesh
        geometry={nodes.Mask002_cell108.geometry}
        material={nodes.Mask002_cell108.material}
        position={[1.94, 5.55, -0.62]}
      />
    </group>
  )
}

useGLTF.preload('/mfdoom.glb')
