/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/mfdoom4.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Mask_cell000.geometry}
        material={nodes.Mask_cell000.material}
        position={[1.43, 0.1, 0.51]}
      />
      <mesh
        geometry={nodes.Mask_cell001.geometry}
        material={nodes.Mask_cell001.material}
        position={[-2.1, 2.33, -1.58]}
      />
      <mesh
        geometry={nodes.Mask_cell002.geometry}
        material={nodes.Mask_cell002.material}
        position={[1.13, 1.71, 0.82]}
      />
      <mesh
        geometry={nodes.Mask_cell003.geometry}
        material={nodes.Mask_cell003.material}
        position={[2.33, 0.34, -0.89]}
      />
      <mesh
        geometry={nodes.Mask_cell004.geometry}
        material={nodes.Mask_cell004.material}
        position={[-2.26, 1.06, -1.38]}
      />
      <mesh
        geometry={nodes.Mask_cell005.geometry}
        material={nodes.Mask_cell005.material}
        position={[1.3, -2.24, 0.41]}
      />
      <mesh
        geometry={nodes.Mask_cell006.geometry}
        material={nodes.Mask_cell006.material}
        position={[2.09, -0.42, -0.45]}
      />
      <mesh
        geometry={nodes.Mask_cell007.geometry}
        material={nodes.Mask_cell007.material}
        position={[-0.37, 1.12, -2.78]}
      />
      <mesh
        geometry={nodes.Mask_cell008.geometry}
        material={nodes.Mask_cell008.material}
        position={[1.86, 2.62, -0.32]}
      />
      <mesh
        geometry={nodes.Mask_cell009.geometry}
        material={nodes.Mask_cell009.material}
        position={[-1.65, 2.24, 0.36]}
      />
      <mesh
        geometry={nodes.Mask_cell010.geometry}
        material={nodes.Mask_cell010.material}
        position={[-0.88, 3.16, -0.59]}
      />
      <mesh
        geometry={nodes.Mask_cell011.geometry}
        material={nodes.Mask_cell011.material}
        position={[1.23, 1.29, 0.9]}
      />
      <mesh
        geometry={nodes.Mask_cell012.geometry}
        material={nodes.Mask_cell012.material}
        position={[1.19, -3.01, 0.3]}
      />
      <mesh
        geometry={nodes.Mask_cell013.geometry}
        material={nodes.Mask_cell013.material}
        position={[-0.29, 0.85, 1.18]}
      />
      <mesh
        geometry={nodes.Mask_cell014.geometry}
        material={nodes.Mask_cell014.material}
        position={[1.59, -0.82, 0.17]}
      />
      <mesh
        geometry={nodes.Mask_cell015.geometry}
        material={nodes.Mask_cell015.material}
        position={[0.34, 0.24, 1.23]}
      />
      <mesh
        geometry={nodes.Mask_cell016.geometry}
        material={nodes.Mask_cell016.material}
        position={[1.85, 2.61, -0.07]}
      />
      <mesh
        geometry={nodes.Mask_cell017.geometry}
        material={nodes.Mask_cell017.material}
        position={[-2.28, 1.67, -1.36]}
      />
      <mesh
        geometry={nodes.Mask_cell018.geometry}
        material={nodes.Mask_cell018.material}
        position={[1.02, 1.26, -2.6]}
      />
      <mesh
        geometry={nodes.Mask_cell019.geometry}
        material={nodes.Mask_cell019.material}
        position={[-1.33, -2.27, 0.38]}
      />
      <mesh
        geometry={nodes.Mask_cell020.geometry}
        material={nodes.Mask_cell020.material}
        position={[-1.51, 2.8, -0.76]}
      />
      <mesh
        geometry={nodes.Mask_cell021.geometry}
        material={nodes.Mask_cell021.material}
        position={[-1.39, 0.32, 0.46]}
      />
      <mesh
        geometry={nodes.Mask_cell022.geometry}
        material={nodes.Mask_cell022.material}
        position={[1.76, 1.44, 0.39]}
      />
      <mesh
        geometry={nodes.Mask_cell023.geometry}
        material={nodes.Mask_cell023.material}
        position={[-1.94, 1.98, -2.14]}
      />
      <mesh geometry={nodes.Mask_cell024.geometry} material={nodes.Mask_cell024.material} position={[1.33, -3, 0.2]} />
      <mesh
        geometry={nodes.Mask_cell025.geometry}
        material={nodes.Mask_cell025.material}
        position={[-0.96, -1.52, 0.95]}
      />
      <mesh
        geometry={nodes.Mask_cell026.geometry}
        material={nodes.Mask_cell026.material}
        position={[-0.64, 2.49, 1.06]}
      />
      <mesh
        geometry={nodes.Mask_cell027.geometry}
        material={nodes.Mask_cell027.material}
        position={[0.23, 3.11, 1.33]}
      />
      <mesh
        geometry={nodes.Mask_cell028.geometry}
        material={nodes.Mask_cell028.material}
        position={[1.36, 1.4, -2.49]}
      />
      <mesh
        geometry={nodes.Mask_cell029.geometry}
        material={nodes.Mask_cell029.material}
        position={[0.39, 1.32, -2.84]}
      />
      <mesh
        geometry={nodes.Mask_cell030.geometry}
        material={nodes.Mask_cell030.material}
        position={[0.16, 0.87, 1.31]}
      />
      <mesh
        geometry={nodes.Mask_cell031.geometry}
        material={nodes.Mask_cell031.material}
        position={[-1.22, 1.18, 0.84]}
      />
      <mesh
        geometry={nodes.Mask_cell032.geometry}
        material={nodes.Mask_cell032.material}
        position={[-1.39, -1.42, 0.37]}
      />
      <mesh
        geometry={nodes.Mask_cell033.geometry}
        material={nodes.Mask_cell033.material}
        position={[-1.95, 1.35, 0.11]}
      />
      <mesh
        geometry={nodes.Mask_cell034.geometry}
        material={nodes.Mask_cell034.material}
        position={[2.23, 0.97, -1.5]}
      />
      <mesh
        geometry={nodes.Mask_cell035.geometry}
        material={nodes.Mask_cell035.material}
        position={[-2.31, 0.76, -0.86]}
      />
      <mesh
        geometry={nodes.Mask_cell036.geometry}
        material={nodes.Mask_cell036.material}
        position={[2.19, 2.1, -0.39]}
      />
      <mesh
        geometry={nodes.Mask_cell037.geometry}
        material={nodes.Mask_cell037.material}
        position={[-1.5, -0.08, 0.56]}
      />
      <mesh
        geometry={nodes.Mask_cell038.geometry}
        material={nodes.Mask_cell038.material}
        position={[0.47, 1.84, 1.19]}
      />
      <mesh
        geometry={nodes.Mask_cell039.geometry}
        material={nodes.Mask_cell039.material}
        position={[-0.82, 1.32, -2.72]}
      />
      <mesh
        geometry={nodes.Mask_cell040.geometry}
        material={nodes.Mask_cell040.material}
        position={[1.34, -3.09, 0.4]}
      />
      <mesh
        geometry={nodes.Mask_cell041.geometry}
        material={nodes.Mask_cell041.material}
        position={[0.54, 1.16, 1.11]}
      />
      <mesh
        geometry={nodes.Mask_cell042.geometry}
        material={nodes.Mask_cell042.material}
        position={[2.07, 1.17, -0.16]}
      />
      <mesh
        geometry={nodes.Mask_cell043.geometry}
        material={nodes.Mask_cell043.material}
        position={[2, -0.29, -0.32]}
      />
      <mesh
        geometry={nodes.Mask_cell044.geometry}
        material={nodes.Mask_cell044.material}
        position={[-1.23, 2.97, 0.57]}
      />
      <mesh
        geometry={nodes.Mask_cell045.geometry}
        material={nodes.Mask_cell045.material}
        position={[-1.79, 1.89, 0.44]}
      />
      <mesh
        geometry={nodes.Mask_cell046.geometry}
        material={nodes.Mask_cell046.material}
        position={[-0.24, -1.07, 1.2]}
      />
      <mesh
        geometry={nodes.Mask_cell047.geometry}
        material={nodes.Mask_cell047.material}
        position={[-0.86, 1.3, 0.99]}
      />
      <mesh
        geometry={nodes.Mask_cell048.geometry}
        material={nodes.Mask_cell048.material}
        position={[0.93, -2.82, 0.95]}
      />
      <mesh
        geometry={nodes.Mask_cell049.geometry}
        material={nodes.Mask_cell049.material}
        position={[-0.04, -0.69, 1.55]}
      />
      <mesh
        geometry={nodes.Mask_cell050.geometry}
        material={nodes.Mask_cell050.material}
        position={[-1.96, 0.38, -0.06]}
      />
      <mesh
        geometry={nodes.Mask_cell051.geometry}
        material={nodes.Mask_cell051.material}
        position={[0.81, 3.1, -0.36]}
      />
      <mesh
        geometry={nodes.Mask_cell052.geometry}
        material={nodes.Mask_cell052.material}
        position={[0.45, 3.34, 1.03]}
      />
      <mesh
        geometry={nodes.Mask_cell053.geometry}
        material={nodes.Mask_cell053.material}
        position={[-1.67, -0.68, 0.11]}
      />
      <mesh
        geometry={nodes.Mask_cell054.geometry}
        material={nodes.Mask_cell054.material}
        position={[0.78, 1.43, -2.78]}
      />
      <mesh
        geometry={nodes.Mask_cell055.geometry}
        material={nodes.Mask_cell055.material}
        position={[-0.07, 3.51, 1.17]}
      />
      <mesh
        geometry={nodes.Mask_cell056.geometry}
        material={nodes.Mask_cell056.material}
        position={[0.22, 0.52, 1.1]}
      />
      <mesh
        geometry={nodes.Mask_cell057.geometry}
        material={nodes.Mask_cell057.material}
        position={[-2.32, 1.83, -0.71]}
      />
      <mesh
        geometry={nodes.Mask_cell058.geometry}
        material={nodes.Mask_cell058.material}
        position={[0.56, 1.02, -2.75]}
      />
      <mesh
        geometry={nodes.Mask_cell059.geometry}
        material={nodes.Mask_cell059.material}
        position={[2.34, 1.61, -0.97]}
      />
      <mesh
        geometry={nodes.Mask_cell060.geometry}
        material={nodes.Mask_cell060.material}
        position={[-0.99, -0.62, 0.9]}
      />
      <mesh
        geometry={nodes.Mask_cell061.geometry}
        material={nodes.Mask_cell061.material}
        position={[-0.96, -2.93, 0.9]}
      />
      <mesh
        geometry={nodes.Mask_cell062.geometry}
        material={nodes.Mask_cell062.material}
        position={[-1.6, 2.83, -1.23]}
      />
      <mesh
        geometry={nodes.Mask_cell063.geometry}
        material={nodes.Mask_cell063.material}
        position={[-0.28, 1.46, 1.23]}
      />
      <mesh
        geometry={nodes.Mask_cell064.geometry}
        material={nodes.Mask_cell064.material}
        position={[2.3, 0.79, -0.68]}
      />
      <mesh
        geometry={nodes.Mask_cell065.geometry}
        material={nodes.Mask_cell065.material}
        position={[-2.37, 0.76, -1.18]}
      />
      <mesh
        geometry={nodes.Mask_cell066.geometry}
        material={nodes.Mask_cell066.material}
        position={[-0.17, 3.31, -0.35]}
      />
      <mesh
        geometry={nodes.Mask_cell067.geometry}
        material={nodes.Mask_cell067.material}
        position={[2.3, 0.05, -0.54]}
      />
      <mesh
        geometry={nodes.Mask_cell068.geometry}
        material={nodes.Mask_cell068.material}
        position={[0.88, -1.25, 0.93]}
      />
      <mesh
        geometry={nodes.Mask_cell069.geometry}
        material={nodes.Mask_cell069.material}
        position={[-2.07, 2.37, -1.1]}
      />
      <mesh
        geometry={nodes.Mask_cell070.geometry}
        material={nodes.Mask_cell070.material}
        position={[0.04, 0.99, 1.18]}
      />
      <mesh
        geometry={nodes.Mask_cell071.geometry}
        material={nodes.Mask_cell071.material}
        position={[-1.24, 1.48, -2.56]}
      />
      <mesh
        geometry={nodes.Mask_cell072.geometry}
        material={nodes.Mask_cell072.material}
        position={[1.51, 2.41, 0.37]}
      />
      <mesh
        geometry={nodes.Mask_cell073.geometry}
        material={nodes.Mask_cell073.material}
        position={[-1.32, -3.04, 0.18]}
      />
      <mesh
        geometry={nodes.Mask_cell074.geometry}
        material={nodes.Mask_cell074.material}
        position={[-1.74, 2.76, -1.29]}
      />
      <mesh
        geometry={nodes.Mask_cell075.geometry}
        material={nodes.Mask_cell075.material}
        position={[1.7, 2.71, -1.09]}
      />
      <mesh
        geometry={nodes.Mask_cell076.geometry}
        material={nodes.Mask_cell076.material}
        position={[0.58, 3.33, -0.64]}
      />
      <mesh
        geometry={nodes.Mask_cell077.geometry}
        material={nodes.Mask_cell077.material}
        position={[-0.46, 3.3, 1.13]}
      />
      <mesh
        geometry={nodes.Mask_cell078.geometry}
        material={nodes.Mask_cell078.material}
        position={[-0.34, -0.41, 1.38]}
      />
      <mesh
        geometry={nodes.Mask_cell079.geometry}
        material={nodes.Mask_cell079.material}
        position={[-1.17, 1.85, 0.85]}
      />
      <mesh
        geometry={nodes.Mask_cell080.geometry}
        material={nodes.Mask_cell080.material}
        position={[-1.82, 1.29, -2.11]}
      />
      <mesh
        geometry={nodes.Mask_cell081.geometry}
        material={nodes.Mask_cell081.material}
        position={[0.69, -0.45, 1.12]}
      />
      <mesh
        geometry={nodes.Mask_cell082.geometry}
        material={nodes.Mask_cell082.material}
        position={[-2.26, 0.07, -0.62]}
      />
      <mesh
        geometry={nodes.Mask_cell083.geometry}
        material={nodes.Mask_cell083.material}
        position={[-1.91, 2.61, -0.34]}
      />
      <mesh
        geometry={nodes.Mask_cell084.geometry}
        material={nodes.Mask_cell084.material}
        position={[-2.14, 2.3, -0.35]}
      />
      <mesh
        geometry={nodes.Mask_cell085.geometry}
        material={nodes.Mask_cell085.material}
        position={[2.11, 1.44, -1.78]}
      />
      <mesh
        geometry={nodes.Mask_cell086.geometry}
        material={nodes.Mask_cell086.material}
        position={[1.1, -3.07, 0.63]}
      />
      <mesh
        geometry={nodes.Mask_cell087.geometry}
        material={nodes.Mask_cell087.material}
        position={[-1.25, -2.95, 0.36]}
      />
      <mesh
        geometry={nodes.Mask_cell088.geometry}
        material={nodes.Mask_cell088.material}
        position={[-1.34, 3.01, -1.05]}
      />
      <mesh
        geometry={nodes.Mask_cell089.geometry}
        material={nodes.Mask_cell089.material}
        position={[-1.71, 2.59, 0.04]}
      />
      <mesh
        geometry={nodes.Mask_cell090.geometry}
        material={nodes.Mask_cell090.material}
        position={[1.98, 0.35, -0.06]}
      />
      <mesh
        geometry={nodes.Mask_cell091.geometry}
        material={nodes.Mask_cell091.material}
        position={[-0.52, 0.21, 1.04]}
      />
      <mesh
        geometry={nodes.Mask_cell092.geometry}
        material={nodes.Mask_cell092.material}
        position={[-1.91, 2.62, -1.42]}
      />
      <mesh
        geometry={nodes.Mask_cell093.geometry}
        material={nodes.Mask_cell093.material}
        position={[-1.08, 0.06, 0.79]}
      />
      <mesh
        geometry={nodes.Mask_cell094.geometry}
        material={nodes.Mask_cell094.material}
        position={[-1.51, 1.28, 0.63]}
      />
      <mesh
        geometry={nodes.Mask_cell095.geometry}
        material={nodes.Mask_cell095.material}
        position={[0.14, 1.23, -2.86]}
      />
      <mesh
        geometry={nodes.Mask_cell096.geometry}
        material={nodes.Mask_cell096.material}
        position={[1.91, 2.03, -2.05]}
      />
      <mesh
        geometry={nodes.Mask_cell097.geometry}
        material={nodes.Mask_cell097.material}
        position={[1.77, 1.35, -2.19]}
      />
      <mesh
        geometry={nodes.Mask_cell098.geometry}
        material={nodes.Mask_cell098.material}
        position={[1.06, 2.94, 0.72]}
      />
      <mesh
        geometry={nodes.Mask_cell099.geometry}
        material={nodes.Mask_cell099.material}
        position={[1.16, -3.18, 0.33]}
      />
      <mesh
        geometry={nodes.Mask_cell103.geometry}
        material={nodes.Mask_cell103.material}
        position={[2.2, 2.18, -1.1]}
      />
      <mesh
        geometry={nodes.Mask_cell105.geometry}
        material={nodes.Mask_cell105.material}
        position={[-0.23, 0.36, 1.31]}
      />
      <mesh
        geometry={nodes.Mask_cell106.geometry}
        material={nodes.Mask_cell106.material}
        position={[-2.2, 2.32, -0.79]}
      />
      <mesh
        geometry={nodes.Mask_cell107.geometry}
        material={nodes.Mask_cell107.material}
        position={[-1.39, -2.7, 0.12]}
      />
    </group>
  )
}

useGLTF.preload('/mfdoom4.glb')
